server.port: 8086
mybatis:
  type-aliases-package:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://8.136.136.248:3306/assess?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
 #servlet:
      #multipart:
      # max-file-size: 10MB #单个文件最大值
      #max-request-size: 20MB #一次请求上传的最大值